### PR TITLE
Use just aur pkg names instead of full link

### PR DESCRIPTION
**Pull request by qopz**
Use simple python script to generate full aur links to packages with just their names

### CODE REVIEW

**Comment by sessionm21** [comment]
Good idea, I like to fetch PKGBUILDS directly from other git repos so I could likely implement both with or without full url. Though I would implement this in BASH for consistency.

**Comment by Dogcatfee** [comment]
Good idea, I like to fetch PKGBUILDS directly from other git repos so I could likely implement both with or without full url. Though I would implement this in BASH for consistency.

**Comment by qopz** [comment]
im not well familiar with bash, and feeling python a way more comfortable and readable, so i consider writing py scripts that generate bash files is a good solution bt not sure it right

**Comment by Dogcatfee** [comment]
I'm still not familiar with BASH myself, but i pushed some new stuff.

**Comment by Dogcatfee** [comment]
Closing this for now

**Pull request closed without merging**
